fos_rest:
  format_listener:
    rules:
      - { path: '^/api', priorities: [ json ], fallback_format: json, prefer_extension: false }
      - { path: '^/', priorities: [ 'text/html', '*/*' ], fallback_format: html, prefer_extension: false }
  param_fetcher_listener: force
  view:
    view_response_listener: force
    formats:
      json: true
      html: true