version: '3'

services:
  db:
    image: mysql:8.0.20
    container_name: "tournament-db"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
    - 3311:3306
    volumes:
    - "./tournament_db:/var/lib/mysql"

  php:
    build:
      context: .
      dockerfile: docker/php/.DockerFile
    container_name: tournament-php
    volumes:
    - ./:/var/www/symfony

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/.DockerFile
    volumes:
      - ./:/var/www/symfony/
    ports:
    - 8001:80
